const mockData = [
{
  id: 1,
  Name: "Carmina Pimlott",
  email: "cpimlott0@epa.gov",
  Password: "By3LPc",
  Behavior: "knowledge base",
  Age: 23,
  Size: "XS",
  Medications: true,
  Disabled: false,
  Sex: "Female",
  Activity_Level: "challenge",
  Breed: "Python, carpet",
  Days_In_Shelter: 45,
  Fur_Type: "eget"
// }, {
//   "id": 2,
//   "Name": "Dosi Mation",
//   "email": "dmation1@webmd.com",
//   "Password": "kdxgayWky",
//   "Behavior": "Open-architected",
//   "Age": 3,
//   "Size": "M",
//   "Medications": true,
//   "Disabled": true,
//   "Sex": "Female",
//   "Activity_Level": "solution",
//   "Breed": "Snake, eastern indigo",
//   "Days_In_Shelter": 32,
//   "Fur_Type": "sapien"
// }, {
//   "id": 3,
//   "Name": "Dallis Plewes",
//   "email": "dplewes2@feedburner.com",
//   "Password": "grwWeZkbwbI",
//   "Behavior": "systematic",
//   "Age": 9,
//   "Size": "L",
//   "Medications": false,
//   "Disabled": true,
//   "Sex": "Female",
//   "Activity_Level": "maximized",
//   "Breed": "Water monitor",
//   "Days_In_Shelter": 26,
//   "Fur_Type": "ut"
// }, {
//   "id": 4,
//   "Name": "Carlene Georghiou",
//   "email": "cgeorghiou3@fema.gov",
//   "Password": "uHOKgO1p9",
//   "Behavior": "Enhanced",
//   "Age": 16,
//   "Size": "M",
//   "Medications": true,
//   "Disabled": true,
//   "Sex": "Male",
//   "Activity_Level": "matrix",
//   "Breed": "Fox, silver-backed",
//   "Days_In_Shelter": 30,
//   "Fur_Type": "sed"
// }, {
//   "id": 5,
//   "Name": "Sammie Franiak",
//   "email": "sfraniak4@arstechnica.com",
//   "Password": "EdOTw2",
//   "Behavior": "database",
//   "Age": 13,
//   "Size": "2XL",
//   "Medications": true,
//   "Disabled": false,
//   "Sex": "Female",
//   "Activity_Level": "grid-enabled",
//   "Breed": "Gonolek, burchell's",
//   "Days_In_Shelter": 30,
//   "Fur_Type": "at"
// }, {
//   "id": 6,
//   "Name": "Serena Totton",
//   "email": "stotton5@state.gov",
//   "Password": "DT8Yf7H",
//   "Behavior": "parallelism",
//   "Age": 19,
//   "Size": "S",
//   "Medications": false,
//   "Disabled": true,
//   "Sex": "Female",
//   "Activity_Level": "Enhanced",
//   "Breed": "Goose, spur-winged",
//   "Days_In_Shelter": 11,
//   "Fur_Type": "tortor"
// }, {
//   "id": 7,
//   "Name": "Hanson Shellibeer",
//   "email": "hshellibeer6@yellowpages.com",
//   "Password": "GT0K36",
//   "Behavior": "Synchronised",
//   "Age": 3,
//   "Size": "M",
//   "Medications": false,
//   "Disabled": false,
//   "Sex": "Male",
//   "Activity_Level": "clear-thinking",
//   "Breed": "Marshbird, brown and yellow",
//   "Days_In_Shelter": 21,
//   "Fur_Type": "vulputate"
// }, {
//   "id": 8,
//   "Name": "Garreth Dacres",
//   "email": "gdacres7@dedecms.com",
//   "Password": "xiDW47N9Ypym",
//   "Behavior": "Grass-roots",
//   "Age": 11,
//   "Size": "L",
//   "Medications": true,
//   "Disabled": true,
//   "Sex": "Male",
//   "Activity_Level": "Programmable",
//   "Breed": "Groundhog",
//   "Days_In_Shelter": 45,
//   "Fur_Type": "quisque"
// }, {
//   "id": 9,
//   "Name": "Morena Greg",
//   "email": "mgreg8@patch.com",
//   "Password": "ta2Sau",
//   "Behavior": "migration",
//   "Age": 16,
//   "Size": "3XL",
//   "Medications": false,
//   "Disabled": true,
//   "Sex": "Female",
//   "Activity_Level": "bifurcated",
//   "Breed": "Sea birds (unidentified)",
//   "Days_In_Shelter": 25,
//   "Fur_Type": "quisque"
// }, {
//   "id": 10,
//   "Name": "Jacklyn Salling",
//   "email": "jsalling9@free.fr",
//   "Password": "ao34TnRnzEr",
//   "Behavior": "Graphic Interface",
//   "Age": 21,
//   "Size": "M",
//   "Medications": false,
//   "Disabled": true,
//   "Sex": "Female",
//   "Activity_Level": "adapter",
//   "Breed": "Polecat, african",
//   "Days_In_Shelter": 21,
//   "Fur_Type": "fusce"
}]